// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapp.Server;

#nullable disable

namespace webapp.Server.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20240523005700_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("webapp.Server.Item", b =>
                {
                    b.Property<ulong>("UPC")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("UPC");

                    b.ToTable("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
